services:
  'example-domain':
    extends:
      file: './domain/docker-compose.yml'
      service: 'domain'
    container_name: 'example-domain'
    command: [
      "mitmdump",
      # Replace example.com with the domain to spoof
      "--mode", "reverse:https://www.example.com@8080",
      "-w", "/logs/example.bin"
    ]
  'dns':
    container_name: 'dns'
    restart: 'unless-stopped'
    image: 'mitmproxy/mitmproxy:12.2.1'
    command: [ "mitmdump", "--mode", "dns@53" ]
    environment:
      # https://github.com/mitmproxy/mitmproxy/issues/7986
      - PYTHONUNBUFFERED=1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    volumes:
      - type: 'bind'
        source: '/etc/localtime'
        target: '/etc/localtime'
        read_only: true
    sysctls:
      - 'net.ipv6.conf.all.disable_ipv6=0'
    extra_hosts:
      # Replace example.com with the domain to spoof
      - 'example.com:127.0.0.1'
      - 'example.com:[::1]'
      - 'www.example.com:127.0.0.1'
      - 'www.example.com:[::1]'
networks:
  default:
    enable_ipv4: true
    enable_ipv6: true
