server {
    listen       80;
    listen  [::]:80;
    server_name  domain;

    access_log  /var/log/nginx/host.access.log  main;
    error_log   /var/log/nginx/host.error.log   warn;

    # location / {
    #     proxy_pass http://example.com;
    # }
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}
